spring:
  application:
    name: technical-test-renderer
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
server:
  port: 8087

webclient:
  api:
    technical:
      port: 8086
      url: http://localhost:${webclient.api.technical.port}
      base-path: /
      flight-path: /flight

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: DEBUG
